### ISSUE TITLE
Where could I see the version of etcd used in quorum?

### ISSUE THREAD

**Issue by hejianhui** [Consensys-Incorporated/quorum#1001]
I want to find the version of etcd used in quorum in the raft consensus, but it seems not in the vendor/vendor.json.

Where could I find it?

**Comment by amalrajmani** [comment]
Hi @hejianhui 
We use raft version 3.3.13, Its source root dir: _vendor/github.com/coreos_
You can find raft version in _vendor/github.com/coreos/etcd/version/version.go_.
Raft has not been integrated via _vendor.json_ because we have done a minor customisation in _vendor/github.com/coreos/etcd/raft/node.go_ to read raft leader role change and this change is required to start/stop block minting from leader node in quorum.

**Comment by hejianhui** [comment]
> Hi @hejianhui
> We use raft version 3.3.13, Its source root dir: _vendor/github.com/coreos_
> You can find raft version in _vendor/github.com/coreos/etcd/version/version.go_.
> Raft has not been integrated via _vendor.json_ because we have done a minor customisation in _vendor/github.com/coreos/etcd/raft/node.go_ to read raft leader role change and this change is required to start/stop block minting from leader node in quorum.

I've found it. Thank you!

**Comment by prd-fox** [comment]
@hejianhui is there a reason you reopened this issue?

If so, please reopen and comment why it's reopened.
