### ISSUE TITLE
private contracts without transaction manager(tessera)

### ISSUE THREAD

**Issue by melihbirim** [Consensys-Incorporated/quorum#1010]
Hi there,

If I want to hide data to other parties I need to use Private Contracts. However, adding a transaction manager to a Quorum network which needs only private transactions in local nodes the transaction manager adds overall operational cost to run the network. In our situation, with 20 nodes network, the operational costs are doubled.

Current need is to store data privately in my local node, and if anyone asks for data, I open it by revealing the data to everyone with hash consistency check on contract level. 

So, without using an external transaction manager, I want to use privateFor locally.

Is it possible in the current system? If yes how it is working, if not would it be possible to add it to feature lists.

Thanks.

**Comment by fixanoid** [comment]
Hey @melihbirim thanks for asking.

We do support several modes that may be helpful to you. First of all, you don't have to have every node run Tessera -- if privacy needs to be guaranteed only by a few nodes, you should only run Tessera with those nodes.

Second, when Tessera is present, you can then create and execute a private contract for own node only. You do this but providing an empty `privateFor: []` which implies just the origin node. Paired with the above system this could fit into your model.

Finally, what you are thinking is a somewhat lighter implementation of Tessera except without Tessera. These are commonly referred to as Zero Knowledge Proofs and there is quiet a few that may be applicable here. Commonly, on Ethereum mainnet they are all limited due to the block size, on Quorum however, there is no such limitation, so it may be possible to build something with that in mind.
