### ISSUE TITLE
send private transaction

### ISSUE THREAD

**Issue by Mohammed-alzuharey** [Consensys-Incorporated/quorum#1059]
Hi everyone
 I need to send private transaction between 2 nodes on  2 vms ... how  can  do that ... any one can help me ? thanks

**Comment by SatpalSandhu61** [comment]
Question answered on [Slack](https://go-quorum.slack.com/archives/C825QTQ1Z/p1597670952068500):
If you want to run the 7 nodes examples on 2 virtual machines, you can start from the following

1. Clone the 7 nodes example repo on the 2 machines
2. Decide what nodes you want to run first machine and what nodes to run on the second machine
3. Update permissioned-nodes.json with the ip addresses of the 2 machines, based on the decision made in step 2
4. Update tessera-init.sh so that you only process nodes for the decision made in step 2. Also make sure to update the ip addresses to the virtual machine ip
5. Update raft-init.sh and raft-start.sh if using raft consensus or istanbul-init.sh and istanbul-start.sh for istanbul consensus so that you only initialize or start nodes that are relevant to that virtual machine
6. Double check the ip addresses in the configuration files, init/start scripts and make sure that they are pointing to the ip addresses of the nodes and not to localhost or 127.0.0.1
