### ISSUE TITLE
Current full block not old enough, what's wrong?

### ISSUE THREAD

**Issue by ScottGold** [Consensys-Incorporated/quorum#1087]
Hi there,

Please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth version`
 Geth
Version: 1.9.7-stable
Git Commit: 6005360c90b636ba0fdc5a18ab308b3df2aa289f
Quorum Version: 2.7.0
Architecture: amd64
Protocol Versions: [64 63]
Network Id: 1337
Go Version: go1.9.7

OS & Version: Linux/

Branch, Commit Hash or Release: `git status`

#### Backtrace

````
[backtrace]
````

**Comment by vsmk98** [comment]
Hi @ScottGold - This is a debug message that will be in the logs. Please correct me if otherwise. 

`geth` version 1.9.0 introduced the concept of freezer db which moves blocks and receipts that are older than a cutoff threshold out of LevelDB into a custom freezer database. Please refer to  https://blog.ethereum.org/2019/07/10/geth-v1-9-0/ for further information on this.
In Quorum the threshold value is set to 3162240. This value can be changed with `geth` start up flag `immutabilitythreshold`
```
--immutabilitythreshold value       overrides the default immutability threshold for Quorum nodes. Its the threshold beyond which block data will be moved to ancient db (default: 3162240)
```
Internally `geth` checks if the block height has reached the threshold value periodically before moving blocks and receipts to freezer db. If the threshold value is not reached the above message will appear in the logs.

**Comment by vsmk98** [comment]
Closing this. 
PS: If you have any questions about Quorum, please ask those on our slack channel as the question might be answered quicker there. Please use github for issue tracking purposes.
