### ISSUE TITLE
Getting error - help required

### ISSUE THREAD

**Issue by aasomani** [Consensys-Incorporated/quorum#109]
#### System information

Geth version: `geth version` - 1.6.0 stable - facc47cb

OS & Version: Linux - ubuntu 12.1 

Branch, Commit Hash or Release: `git status` - On branch master

#### Expected behaviour
git clone https://github.com/jpmorganchase/quorum.git
cd quorum
make all
---should not give error
#### Actual behaviour
It is giving error

build/env.sh go run build/ci.go install
build/env.sh: 31: exec: go: not found

I have set-up binaries in .bashprofile file with - /build/bin, /build/geth, build/bootnode

but no success

#### Backtrace

````
[backtrace]
````

**Comment by aasomani** [comment]
Installed Go and issue resolved.

**Comment by tylobban** [comment]
cool. also make sure that `geth version` gives the correct version for quorum (1.5.0-unstable)

**Comment by aasomani** [comment]
Thanks for the direction.
Being a beginner on Quorum, lots of question
1. How do I confirm if its working. Can I start session on the browser to test if everything is working? 
2. Please guide how to turn it private and then start changes on what I would like to implement? 
3. If I create a new ,go script how do I run it and how do I add to the main script so that it is used?
4. How can I add new data if have to input from external sources i.e. flat file?

**Comment by tylobban** [comment]
Hi @aasomani, the best way for you to get started quickly is to run the [7nodes](https://github.com/jpmorganchase/quorum-examples/tree/master/examples/7nodes) example that we have set up.  This starts a cluster of 7 Quorum nodes with corresponding constellation servers and allows you to send transactions into the network, including allowing you to [test privacy](https://github.com/jpmorganchase/quorum-examples/tree/master/examples/7nodes#testing-privacy).

Are you new to Ethereum as well?  If so, then please do check out the [Ethereum](https://github.com/ethereum/wiki/wiki) wiki, [whitepaper](https://github.com/ethereum/wiki/wiki/White-Paper), and perhaps the ethereum subreddit too, which has a host of 'getting started' links pinned.

**Comment by rohitgkr** [comment]
Hi guys. I am not clear about how to encode public keys in privateFor. The documentation says base64. Would that be the coinbase 40 character address in hex converted to base64? Reverse engineering the myseterious "ROAZBWtSacxXQrOe3FGAqJDyJjFePR5ce4TSIzmJ0Bc=" from 7nodes example gives the corresponding hex address '44E019056B5269CC5742B39EDC5180A890F22631'. I did this by taking the 1st 20 bytes from the 32 bytes array of the base64 string. That doesn't correspond to anything! node7 has no coinbase or accounts. eth.getBalance("44E019056B5269CC5742B39EDC5180A890F22631") = 0.
Can you please cl;arify on privateFor encoding and what entity the address corresponds to?
Thanks.

**Comment by patrickmn** [comment]
The privateFor public keys are the (base64-encoded) NaCl public keys used by Constellation, the Private Transaction Manager. They are distinct from Ethereum keypairs/account addresses.

In the 7nodes example, you would send to the contents of [one of the tm*.pub files](https://github.com/jpmorganchase/quorum-examples/tree/master/examples/7nodes/keys).

**Comment by rohitgkr** [comment]
Thanks @patrickmn, that makes sense and each constellation node has its own public key. So the private stateDB is then specific to the constellation node rather than any ethereum address which also makes sense.
However I am baffled by the following. In the 7Nodes example when I attach geth to nodes 1 & 7 I can see the private contract on both using - 
eth.getCode("0x1932c48b2bf8102ba33b4a6b545c32236e342f34")
I paused the blockmaker (quarum.pauseBlockmaker) & did an eth.blockNumber on nodes 1 & 7. 
node1 => 584 & node7 => 12892. Also when I attached to node2 (nodeInfo blockMaker) the blockNumber is 13123! My understanding is node2 is a block maker, nodes (2,4,5) are voters. But shouldn't all nodes 1 to 7 have the same block chain copy which means all should return 13123 as the block head? Is this standard behaviour or have things gone out of sync since I have been using pauseBlockmaker & resumeBlockmaker?

**Comment by tylobban** [comment]
Every node should have the same block number, so something has gone out of sync. If you can regenerate this then please send through the details so we can see if there is an issue. 

Also, constellation keys are generated as per the instructions here: https://github.com/jpmorganchase/constellation/blob/master/README.md

**Comment by rohitgkr** [comment]
Thanks @tylobban. 
IMO generating empty blocks continuously is wasteful, so I am thinking of resuming a paused block maker after submitting a transaction & polling till a non null transaction receipt. Once receipt is returned I'll pause the block maker. 
Is there any risk or known issue with using this approach? Is there a possibility that constellation nodes will not be in sync using pause & resume? My assumption is that when a block is mined, pausing the block maker should not stall the ethereum nodes from adding the block to their chain copies?

**Comment by tylobban** [comment]
@rohitgkr that approach is fine, and [others](https://github.com/coeniebeyers/QuorumNetworkManager/blob/master/pauseBlockMaking.js) have done that. The reason block creation continues is because QuorumChain consensus is fork-allowing (in a multi-maker setup), and so continuous block creation helps secure historical blocks from a malicious actor. Of course the raft consensus mechanism does not allow forks and so block creation is on demand.
