### ISSUE TITLE
How does the network decide on block-makers and voters?

### ISSUE THREAD

**Issue by oleiba** [Consensys-Incorporated/quorum#131]
Hi, I have looked into the 7nodes example, where some nodes are configured as block-makers and voters.
I'll be happy to get some clarification about how this process works.

It seems that configuring a node with some role (block-maker or voter) is done by copying a keys file into the specific node keystore directory.
I see every such key file has an address, which will later be referenced as the role account address, e.g. `blockMakerAccount`.

1. What exactly in this key file make such a node a block-maker (or voter) ?
2. How can a node become a block-maker \ voter  at some point later than initial configuration?
    Does it require some kind of network voting \ consensus in order for him to join?
3. According to the [RAFT-Protocol docs](https://github.com/jpmorganchase/quorum/blob/master/raft/doc.md) there can be only one leader at a given time, where by default (and preference, per the docs) is also a minter, which transmits the blocks.
   Is there any mechanism for preventing DoS \ censorship of transactions by a minter?
4. From the [RAFT-Protocol docs](https://github.com/jpmorganchase/quorum/blob/master/raft/doc.md#on-every-node): 
> At this point, Raft comes to consensus and appends the log entry containing our block to the Raft log. (The way this happens at the Raft layer is that the leader sends an AppendEntries to all followers, and they acknowledge receipt of the message. Once the leader has received a quorum of such acknowledgements, it notifies each node that this new entry has been committed permanently to the log).

  Are the nodes which _acknowledge_ the `AppendEntries` message, must be voters? Or all nodes within the network?

**Comment by oleiba** [comment]
Hi, after digging a bit further into the 7nodes example, I think I was able to find a few answers to my questions. It will be highly appreciated if I can have those confirmed.
> 1. What exactly in this key file make such a node a block-maker (or voter) ?
> 2. How can a node become a block-maker \ voter at some point later than initial configuration?
Does it require some kind of network voting \ consensus in order for him to join?

In [quorum-examples/examples/7nodes/init.sh](https://github.com/jpmorganchase/quorum-examples/blob/master/examples/7nodes/init.sh) each node is optionally given key files into their keystore directory which consist of their account address and key-derivation function and parameters.
Now I think that `genesis.json`, among holding some account addresses and their initial balances (so they would be able to later pay gas) - is also allocating initial EVM code.
Now, it's impossible to decompile that code back to solidity, but I assume it actually deploys the contract of [quorum/core/quorum/block_voting.sol](https://github.com/jpmorganchase/quorum/blob/6ce61232f951d53e937150fc95cef366a4989f13/core/quorum/block_voting.sol) for adding/removing block-voters and block-makers, which are set to initially be (at least) the account of node no. 2 which is configured to be both block maker and voter.

> 4. Are the nodes which acknowledge the AppendEntries message, must be voters? Or all nodes within the network?

from the same `BlockVoting` contract, I conclude that only voters can vote on blocks. Also, since they can add other voters, they can vote multiple times for a block - thus should be trusted.

**Comment by tylobban** [comment]
Hi @oleiba,

> What exactly in this key file make such a node a block-maker (or voter) ?

It's not the keyfile that determines whether a node is a block maker or voter, it's what is defined in the genesis.json file as described [here](https://github.com/jpmorganchase/quorum/blob/master/docs/running.md#initialize-chain).  Essentially the initial state of the `BlockVoting` contract in block_voting.sol is hardcoded in the genesis.json file.  As can be seen, the 4 voters are defined in the genesis.json - you will not see their addresses directly since the storage key is the `sha3 ` hash of the address and the index of the `canVote` variable. 

> How can a node become a block-maker \ voter at some point later than initial configuration?

By other voters or makers sending a transaction to the `addVoter ` or `addBlockMaker ` functions of the `BlockVoting ` contract.

> According to the RAFT-Protocol docs there can be only one leader at a given time, where by default (and preference, per the docs) is also a minter, which transmits the blocks.
> Is there any mechanism for preventing DoS \ censorship of transactions by a minter?

The raft implementation is deliberately not a Byzantine algorithm and therefore has built in trust assumptions, so these are not accounted for.  We do, however, plan to have a BFT consensus mechanism at some point in the future.

> Are the nodes which acknowledge the AppendEntries message, must be voters? Or all nodes within the network?

You seem to be conflating the QuorumChain consensus mechanism (which has BlockVoters and BlockMakers) with the raft consensus mechanism.  These are two different consensus mechanisms and you can choose which one to run in your network.  For raft, AppendEntries is acknowledged by all other network participants.
