### ISSUE TITLE
You are partly responsible for the financial crisis of 2007/2008 and convicted of fraud several times.  Why would I trust your blockchain code?  This must be fraud.

### ISSUE THREAD

**Issue by spencerlievens** [Consensys-Incorporated/quorum#184]

**Comment by spencerlievens** [comment]
If this Issue is closed without comment, I will reopen it and continue to do so, reassurances and discussion is essential over this matter.

**Comment by ncioj10** [comment]
Do a code review yourself, it's open source!

**Comment by markasoftware** [comment]
While there are lots of reasons not to like JP Morgan, unless you have a direct technical concern this isn't the right place to make a rant. Additionally, if this was closed by a maintainer, you would not be able to reopen it. The code is open source, you don't have to trust them, go look through it.

**Comment by unfurledboredom** [comment]
Because they have this little thing called ALL OUR MONEY, and because they have the power to do this. 

https://news.bitcoin.com/after-the-boss-calls-bitcoin-a-fraud-jp-morgan-buys-the-dip/

With that rant aside, since this is in github, it is our job to go through the code and find the potential bugs or backdoors in the software. 

Also note, this is a version of the Quorum code. The production version of the Quorum code if there is any, may be drastically different.
