### ISSUE TITLE
Issue with block timestamp while running in raft

### ISSUE THREAD

**Issue by paliwalg** [Consensys-Incorporated/quorum#190]
Hi, 

Pulled master of quorum and configured 4 nodes to run the raft consensus.

Able to deploy contracts and perform transaction call on deployed contract in private manner.
Facing issue while fetching block time-stamp. It is returning value as "1506355254821575394", seems to be in non unix format. 
In our solidity contract we are using now to fetch the current timestamp and that is also returning same type of value.  Since now is alias of current block timestamp, so it will definitely return the same value.

Thanks

**Comment by bts** [comment]
Hi Gourav,

The reason the number is so large is that because it's in nanoseconds, not seconds, since epoch. With raft-based consensus we can produce far more than one block per second, which vanilla Ethereum implicitly disallows: the default timestamp resolution is in seconds, and every block must have a timestamp greater than its parent. I will add some documentation mentioning this in the [raft docs](/jpmorganchase/quorum/blob/master/raft/doc.md).

I am going to close it for now, but if you would like, let me know and I can re-open this issue for further discussion.

Thanks!
Brian

**Comment by paliwalg** [comment]
Thanks for the quick response Brian.

**Comment by didil** [comment]
I think this issue should stay open as long as it's not documented ...
