### ISSUE TITLE
Issue in creating privatenet using Ethereum after using Quorum

### ISSUE THREAD

**Issue by mariam-crissi** [Consensys-Incorporated/quorum#245]
#### System information

Geth version: `geth version  1.7.2-stable-0905eda4
`
OS & Version: Linux

I have recently used Quorum Network.I have created private blockchain using Quorum.

Now I am trying to create privatenet using Ethereum network.

      INFO [12-08|16:46:54] Reconfiguring old genesis as Quorum 
      INFO [12-08|16:46:54] Initialised chain configuration          config="{ChainID: 0 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: <nil> EIP155: 0 EIP158: 0 Byzantium: <nil> IsQuorum: true Engine: unknown}"   ```

How can I disable Quorum ```IsQuorum :false``` ?                                                                                          Due to the IsQuorum value,I can't able to do mining in private ethereum network.

This is the issue, I am facing while do mining.

        ERROR[12-11|12:06:56] Failed to prepare header for mining      err="vote nonce not 0x00..0 or 0xff..f"

**Comment by joelburget** [comment]
I'm confused why your Quorum network is mining. The two forms of consensus in Quorum are Raft and Istanbul BFT, and I can't imagine why either would give that error.

I'm also making it more intuitive to set `IsQuorum: false`, but this is a separate issue.

**Comment by patrickmn** [comment]
@mariam-crissi please indicate if #269 doesn't solve your issue.

**Comment by kartikb29** [comment]
Hi all, I am having a problem starting up a quorum network using chaindata created by a private geth network. The data is being read correctly after the network setup and the issue comes up as soon as I submit a new transaction. I get the following error.

panic: failed to extend chain: future block: 1528911882530692583 > 1528913591

error is generated on line 869 of handler.go https://github.com/jpmorganchase/quorum/blob/master/raft/handler.go

Any help is appreciated.

**Comment by MrHmP** [comment]
@kartikeya95 are you using same network with same constellation key pairs?
Because the private data is encrypted in quorum so you cannot plug that data into separate blockchain.
