### ISSUE TITLE
Gas and Transactions

### ISSUE THREAD

**Issue by davebryson** [Consensys-Incorporated/quorum#38]
It appears that no gas is consumed for transactions (gasPrice = 0).  Is this correct?  Yet you need a funded account to send transactions.  Which means if I don't transfer value, I can make as many transaction calls as I like because gas will never reduce my balance.   

Will the use of gas or account balance change in future versions of Quorum or is this the intended design?

**Comment by davoell** [comment]
The use of gas (with gasPrice = 0) is the intended design. We want to prevent infinite loops in the EVM and want DApp developers to be aware of the computation costs associated with their designs, but we don't see cost/benefit justification for reducing balances in a permissioned/consortium network. One future change we've discussed is to automatically pre-fund newly created accounts with an amount of Ether to make things easier since an account with a zero balance cannot send transactions (even though gasPrice = 0). In the mean time you can just do a value transfer from a funded account to new accounts that need to be created.

**Comment by adarshpais** [comment]
Can we do transaction between two coinbase account in quorum @davoell ?
