### ISSUE TITLE
[Question] How to setup limited nodes as Raft consensus nodes?

### ISSUE THREAD

**Issue by KimiWu123** [Consensys-Incorporated/quorum#394]
In the article [here](https://github.com/jpmorganchase/quorum/blob/master/raft/doc.md#initial-configuration-and-enacting-membership-changes), it says

> Currently Raft-based consensus requires that all initial nodes in the cluster are configured to list the others up-front as static peers. These enode ID URIs must include a raftport querystring parameter specifying the raft port for each peer

If I understand correctly, every node needs to be a raft node so every node has a chance to be a leader. In our scenario, we only want  some specific nodes which could be elected as a leader. Is it possible? 

We are still using Quorum v1.2.

Thanks.

**Comment by fixanoid** [comment]
Hi @KimiWu123 since Quorum v2.x supports 2 consensus algos, you should pick one that fits your needs. Raft one does not allow fine grained control on who the minter is since thats all part of the Raft spec. Istanbul algo allows you to pick a set of validators and proposers (or block makers). Please see here: https://github.com/ethereum/EIPs/issues/650 which seems to fit the requirement you have.

**Comment by KimiWu123** [comment]
@fixanoid , Thanks! we know Istanbul, but we aren't sure its performance and stability. Besides, Quorum v2.x applies that accounts with zero balance could send tx if gas price is zero. That is different from v1.x. It needs time for us to adjust our design. Anyway, thanks for your answer!
