### ISSUE TITLE
Erc-20 cryptocurrency exchange integration question

### ISSUE THREAD

**Issue by kirillv** [Consensys-Incorporated/quorum#423]
Hi all.

Sorry for posting here, but cant find any other communication channel.
Can Erc-20 token based on Quorum be integrated in any cryptocurrency exchange (for example Coinbase)?

Thanks in advance

**Comment by tylobban** [comment]
This is technically possible since they would just be ERC20 tokens, but like any new network the exchange would need to operate nodes on the network in order for this to be possible. 

But this is a great question because it highlights one of the key benefits of Quorum: that you can leverage all of the standards that exist in the public Ethereum environment but operate in an environment that is more suitable for business applications. 

And when connectivity to public Ethereum exists you should be able to ‘swap’ Quorum tokens for tokens on Ethereum.

Also, please join our slack :) you can self subscribe here: https://quorumslack.azurewebsites.net/
