### ISSUE TITLE
can not run private-contract.js

### ISSUE THREAD

**Issue by kengan** [Consensys-Incorporated/quorum#432]
I have run 7nodes example without any problem. After I run raft-start.sh , it show ' To test sending a private transaction from Node 1 to Node 7, run './runscript.sh private-contract.js'
I run  ./runscript.sh private-contract.js and get error 

err creating contract Error: Non-200 status code: &{Status:500 Internal Server Error StatusCode:500 Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Date:[Wed, 04 Jul 2018 04:21:50 GMT] Server:[Warp/3.2.13]] Body:0xc424597f40 ContentLength:-1 TransferEncoding:[chunked] Close:false Uncompressed:false Trailer:map[] Request:0xc43f52a700 TLS:<nil>}
true

Can you tell me how to solve this problem? Thank you !

**Comment by kengan** [comment]
Here is the content of  private-contract.js, the key in  privateFor: ["QfeDAys9MPDs2XHExtc84jKGHxZg/aj52DTh0vtA3Xc="] is from  tm2.pub




a = eth.accounts[0]
console.log(a);
web3.eth.defaultAccount = a;

// abi and bytecode generated from simplestorage.sol:
// > solcjs --bin --abi simplestorage.sol
var abi = [{"constant":true,"inputs":[],"name":"storedData","outputs":[{"name":"","type":"uint256"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"x","type":"uint256"}],"name":"set","outputs":[],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"get","outputs":[{"name":"retVal","type":"uint256"}],"payable":false,"type":"function"},{"inputs":[{"name":"initVal","type":"uint256"}],"payable":false,"type":"constructor"}];

var bytecode = "0x6060604052341561000f57600080fd5b604051602080610149833981016040528080519060200190919050505b806000819055505b505b610104806100456000396000f30060606040526000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff1680632a1afcd914605157806360fe47b11460775780636d4ce63c146097575b600080fd5b3415605b57600080fd5b606160bd565b6040518082815260200191505060405180910390f35b3415608157600080fd5b6095600480803590602001909190505060c3565b005b341560a157600080fd5b60a760ce565b6040518082815260200191505060405180910390f35b60005481565b806000819055505b50565b6000805490505b905600a165627a7a72305820d5851baab720bba574474de3d09dbeaabc674a15f4dd93b974908476542c23f00029";

var simpleContract = web3.eth.contract(abi);
var simple = simpleContract.new(42, {from:web3.eth.accounts[0], data: bytecode, gas: 0x47b760, privateFor: ["QfeDAys9MPDs2XHExtc84jKGHxZg/aj52DTh0vtA3Xc="]}, function(e, contract) {
	if (e) {
		console.log("err creating contract", e);
	} else {
		if (!contract.address) {
			console.log("Contract transaction send: TransactionHash: " + contract.transactionHash + " waiting to be mined...");
		} else {
			console.log("Contract mined! Address: " + contract.address);
			console.log(contract);
		}
	}
});

**Comment by SatpalSandhu61** [comment]
A few questions:
Are you running the latest version of the 7nodes example?
Are you running it in the vm or locally?
Are there are any errors in the quorum or constellation log files?
(You could also try doing a clean install and see if that works)

**Comment by kengan** [comment]
SatpalSandhu61 
Thank you for your answer . I use  git clone https://github.com/jpmorganchase/quorum-examples  to get 7nodes example  and I think it is the latest version.
Now I can run the  /runscript.sh private-contract.js without error and get following result:

Contract transaction send: TransactionHash: 0x673c8027ae1c28711b8897c1589bc86ee820671cd87b05817f57f4d9d8916632 waiting to be mined...
true

I want to know how to mine the contract. thank you!

**Comment by SatpalSandhu61** [comment]
Are you running it with Raft? If so, it will automatically get mined (as long as you have at least 3 nodes running).

**Comment by SupwinGary** [comment]
I got the same problem, the log shows the error"out of gas"
nohup: appending output to 'nohup.out'
INFO [07-05|09:32:11] Starting peer-to-peer node               instance=Geth/v1.7.2-stable-df4267a2/linux-amd64/go1.9.3
INFO [07-05|09:32:11] Allocated cache and file handles         database=/root/quorum-examples/examples/7nodes/qdata/dd6/geth/chaindata cache=128 handles=1024
WARN [07-05|09:32:11] Upgrading database to use lookup entries 
INFO [07-05|09:32:11] Initialised chain configuration          config="{ChainID: 10 Homestead: <nil> DAO: <nil> DAOSupport: false EIP150: 1 EIP155: 0 EIP158: 1 Byzantium: 1 IsQuorum: true Engine: unknown}"
INFO [07-05|09:32:11] Disk storage enabled for ethash caches   dir=/root/quorum-examples/examples/7nodes/qdata/dd6/geth/ethash count=3
INFO [07-05|09:32:11] Disk storage enabled for ethash DAGs     dir=/root/.ethash                                               count=2
INFO [07-05|09:32:11] Initialising Ethereum protocol           versions="[63 62]" network=1
INFO [07-05|09:32:11] Database deduplication successful        deduped=0
INFO [07-05|09:32:11] Loaded most recent local header          number=0 hash=6a6605â€¦6243a2 td=0
INFO [07-05|09:32:11] Loaded most recent local full block      number=0 hash=6a6605â€¦6243a2 td=0
INFO [07-05|09:32:11] Loaded most recent local fast block      number=0 hash=6a6605â€¦6243a2 td=0
INFO [07-05|09:32:11] Regenerated local transaction journal    transactions=0 accounts=0
INFO [07-05|09:32:11] Starting P2P networking 
INFO [07-05|09:32:11] RLPx listener up                         self="enode://eacaa74c4b0e7a9e12d2fe5fee6595eda841d6d992c35dbbcc50fcee4aa86dfbbdeff7dc7e72c2305d5a62257f82737a8cffc80474c15c611c037f52db1a3a7b@[::]:21005?discport=0"
INFO [07-05|09:32:11] starting raft protocol handler 
INFO [07-05|09:32:11] loaded the latest applied index          lastAppliedIndex=0
INFO [07-05|09:32:11] replaying WAL 
INFO [07-05|09:32:11] loading WAL                              term=0 index=0
INFO [07-05|09:32:11] startRaft                                raft ID=6
INFO [07-05|09:32:11] starting a new raft log                  initial cluster size of=7
raft2018/07/05 09:32:12 INFO: 6 became follower at term 0
raft2018/07/05 09:32:12 INFO: newRaft 6 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
raft2018/07/05 09:32:12 INFO: 6 became follower at term 1
INFO [07-05|09:32:12] ignoring expected ConfChangeAddNode for initial peer raft id=1
INFO [07-05|09:32:12] start snapshot                           applied index=0 last snapshot index=0
INFO [07-05|09:32:12] compacted log                            index=0
INFO [07-05|09:32:12] persisted the latest applied index       index=1
INFO [07-05|09:32:12] ignoring expected ConfChangeAddNode for initial peer raft id=2
INFO [07-05|09:32:12] start snapshot                           applied index=1 last snapshot index=1
INFO [07-05|09:32:12] compacted log                            index=1
INFO [07-05|09:32:12] persisted the latest applied index       index=2
INFO [07-05|09:32:12] ignoring expected ConfChangeAddNode for initial peer raft id=3
INFO [07-05|09:32:12] start snapshot                           applied index=2 last snapshot index=2
INFO [07-05|09:32:12] compacted log                            index=2
INFO [07-05|09:32:12] persisted the latest applied index       index=3
INFO [07-05|09:32:12] ignoring expected ConfChangeAddNode for initial peer raft id=4
INFO [07-05|09:32:12] start snapshot                           applied index=3 last snapshot index=3
INFO [07-05|09:32:12] compacted log                            index=3
INFO [07-05|09:32:12] persisted the latest applied index       index=4
INFO [07-05|09:32:12] ignoring expected ConfChangeAddNode for initial peer raft id=5
INFO [07-05|09:32:12] start snapshot                           applied index=4 last snapshot index=4
INFO [07-05|09:32:12] compacted log                            index=4
INFO [07-05|09:32:12] persisted the latest applied index       index=5
INFO [07-05|09:32:12] ignoring expected ConfChangeAddNode for initial peer raft id=6
INFO [07-05|09:32:12] start snapshot                           applied index=5 last snapshot index=5
INFO [07-05|09:32:12] compacted log                            index=5
INFO [07-05|09:32:12] persisted the latest applied index       index=6
INFO [07-05|09:32:12] ignoring expected ConfChangeAddNode for initial peer raft id=7
INFO [07-05|09:32:12] start snapshot                           applied index=6 last snapshot index=6
INFO [07-05|09:32:12] compacted log                            index=6
INFO [07-05|09:32:12] persisted the latest applied index       index=7
INFO [07-05|09:32:12] IPC endpoint opened: /root/quorum-examples/examples/7nodes/qdata/dd6/geth.ipc 
INFO [07-05|09:32:12] HTTP endpoint opened: http://0.0.0.0:22005 
raft2018/07/05 09:32:26 INFO: 6 [term: 1] received a MsgVote message with higher term from 2 [term: 2]
raft2018/07/05 09:32:26 INFO: 6 became follower at term 2
raft2018/07/05 09:32:26 INFO: 6 [logterm: 1, index: 7, vote: 0] cast MsgVote for 2 [logterm: 1, index: 7] at term 2
raft2018/07/05 09:32:26 INFO: raft.node: 6 elected leader 2 at term 2
INFO [07-05|09:32:26] QUORUM-CHECKPOINT                        name=BECAME-VERIFIER
INFO [07-05|09:32:26] persisted the latest applied index       index=8
raft2018/07/05 09:34:27 INFO: 6 is starting a new election at term 2
raft2018/07/05 09:34:27 INFO: 6 became candidate at term 3
raft2018/07/05 09:34:27 INFO: 6 received MsgVoteResp from 6 at term 3
raft2018/07/05 09:34:27 INFO: 6 [logterm: 2, index: 8] sent MsgVote request to 4 at term 3
raft2018/07/05 09:34:27 INFO: 6 [logterm: 2, index: 8] sent MsgVote request to 5 at term 3
raft2018/07/05 09:34:27 INFO: 6 [logterm: 2, index: 8] sent MsgVote request to 7 at term 3
raft2018/07/05 09:34:27 INFO: 6 [logterm: 2, index: 8] sent MsgVote request to 1 at term 3
raft2018/07/05 09:34:27 INFO: 6 [logterm: 2, index: 8] sent MsgVote request to 2 at term 3
raft2018/07/05 09:34:27 INFO: 6 [logterm: 2, index: 8] sent MsgVote request to 3 at term 3
raft2018/07/05 09:34:27 INFO: raft.node: 6 lost leader 2 at term 3
INFO [07-05|09:34:27] QUORUM-CHECKPOINT                        name=BECAME-VERIFIER
raft2018/07/05 09:34:27 INFO: 6 received MsgVoteResp from 4 at term 3
raft2018/07/05 09:34:27 INFO: 6 [quorum:4] has received 2 MsgVoteResp votes and 0 vote rejections
raft2018/07/05 09:34:27 INFO: 6 received MsgVoteResp from 7 at term 3
raft2018/07/05 09:34:27 INFO: 6 [quorum:4] has received 3 MsgVoteResp votes and 0 vote rejections
raft2018/07/05 09:34:27 INFO: 6 received MsgVoteResp from 3 at term 3
raft2018/07/05 09:34:27 INFO: 6 [quorum:4] has received 4 MsgVoteResp votes and 0 vote rejections
raft2018/07/05 09:34:27 INFO: 6 became leader at term 3
raft2018/07/05 09:34:27 INFO: raft.node: 6 elected leader 6 at term 3
INFO [07-05|09:34:27] QUORUM-CHECKPOINT                        name=BECAME-MINTER
INFO [07-05|09:34:27] Not minting a new block since there are no pending transactions 
INFO [07-05|09:34:27] persisted the latest applied index       index=9
INFO [07-05|09:34:28] Unlocked account                         address=0xCC71C7546429a13796cf1BF9228bFf213e7Ae9cc
INFO [07-05|09:35:18] Generated next block                     block num=1 num txes=1
INFO [07-05|09:35:18] ðŸ”¨  Mined block                           number=1 hash=7a76989a      elapsed=1.858858ms
INFO [07-05|09:35:18] QUORUM-CHECKPOINT                        name=TX-ACCEPTED     tx=0xae984820de7ae0d3acb15ce819c93bb3539ac08123b063ccfb265d56cf6affb8
INFO [07-05|09:35:21] Generating ethash verification cache     epoch=0 percentage=0 elapsed=3.293s
INFO [07-05|09:35:24] Generating ethash verification cache     epoch=0 percentage=1 elapsed=6.548s
INFO [07-05|09:35:27] Generating ethash verification cache     epoch=0 percentage=2 elapsed=9.689s
INFO [07-05|09:35:31] Generating ethash verification cache     epoch=0 percentage=4 elapsed=12.956s
INFO [07-05|09:35:34] Generating ethash verification cache     epoch=0 percentage=4 elapsed=16.282s
INFO [07-05|09:35:37] Generating ethash verification cache     epoch=0 percentage=4 elapsed=19.561s
INFO [07-05|09:35:40] Generating ethash verification cache     epoch=0 percentage=4 elapsed=22.822s
INFO [07-05|09:35:44] Generating ethash verification cache     epoch=0 percentage=6 elapsed=26.134s
INFO [07-05|09:35:47] Generating ethash verification cache     epoch=0 percentage=6 elapsed=29.382s
INFO [07-05|09:35:50] Generating ethash verification cache     epoch=0 percentage=6 elapsed=32.707s
INFO [07-05|09:35:54] Generating ethash verification cache     epoch=0 percentage=7 elapsed=36.178s
INFO [07-05|09:36:00] Generating ethash verification cache     epoch=0 percentage=7 elapsed=42.478s
INFO [07-05|09:36:03] Generating ethash verification cache     epoch=0 percentage=10 elapsed=45.845s
INFO [07-05|09:36:07] Generating ethash verification cache     epoch=0 percentage=10 elapsed=48.929s
INFO [07-05|09:36:10] Generating ethash verification cache     epoch=0 percentage=10 elapsed=52.082s
INFO [07-05|09:36:13] Generating ethash verification cache     epoch=0 percentage=11 elapsed=55.245s
INFO [07-05|09:36:17] Generating ethash verification cache     epoch=0 percentage=16 elapsed=59.200s
INFO [07-05|09:36:20] Generating ethash verification cache     epoch=0 percentage=17 elapsed=1m2.325s
INFO [07-05|09:36:24] Generating ethash verification cache     epoch=0 percentage=35 elapsed=1m5.985s
INFO [07-05|09:36:26] Generated ethash verification cache      epoch=0 elapsed=1m7.934s
INFO [07-05|09:36:28] Imported new chain segment               blocks=1 txs=1 mgas=0.000 elapsed=1m10.399s  mgasps=0.000 number=1 hash=7a7698â€¦6f9532
INFO [07-05|09:36:28] QUORUM-CHECKPOINT                        name=BLOCK-CREATED   block=7a76989a35d0034c265745bd0ef39351169e67b5969617e052ee2f61686f9532
INFO [07-05|09:36:28] persisted the latest applied index       index=10
INFO [07-05|09:36:28] Not minting a new block since there are no pending transactions 
INFO [07-05|09:42:51] TX failed, will be removed               hash=4909fdâ€¦fa6fea err="out of gas"
INFO [07-05|09:42:51] Not minting a new block since there are no pending transactions 
INFO [07-05|09:49:42] TX failed, will be removed               hash=4909fdâ€¦fa6fea err="out of gas"
INFO [07-05|09:49:42] Not minting a new block since there are no pending transactions 
INFO [07-05|09:54:37] TX failed, will be removed               hash=4909fdâ€¦fa6fea err="out of gas"
INFO [07-05|09:54:37] Not minting a new block since there are no pending transactions 
INFO [07-05|09:58:37] TX failed, will be removed               hash=4909fdâ€¦fa6fea err="out of gas"
INFO [07-05|09:58:37] Not minting a new block since there are no pending transactions 
INFO [07-05|10:07:20] TX failed, will be removed               hash=4909fdâ€¦fa6fea err="out of gas"
INFO [07-05|10:07:20] Not minting a new block since there are no pending transactions 
INFO [07-05|10:23:27] TX failed, will be removed               hash=4909fdâ€¦fa6fea err="out of gas"
INFO [07-05|10:23:27] Not minting a new block since there are no pending transactions 
INFO [07-05|10:28:11] TX failed, will be removed               hash=4909fdâ€¦fa6fea err="out of gas"
INFO [07-05|10:28:11] Not minting a new block since there are no pending transactions 
INFO [07-05|10:30:15] TX failed, will be removed               hash=4909fdâ€¦fa6fea err="out of gas"
INFO [07-05|10:30:15] Not minting a new block since there are no pending transactions 
INFO [07-05|10:32:11] Regenerated local transaction journal    transactions=0 accounts=0
INFO [07-05|10:37:31] TX failed, will be removed               hash=4909fdâ€¦fa6fea err="out of gas"
INFO [07-05|10:37:31] Not minting a new block since there are no pending transactions 
INFO [07-05|10:38:59] TX failed, will be removed               hash=4909fdâ€¦fa6fea err="out of gas"
INFO [07-05|10:38:59] Not minting a new block since there are no pending transactions

**Comment by SupwinGary** [comment]
I am working with kengan testing the 7nodes example.The error ""out of gas" comes after we successfully send the first transaction.

**Comment by kengan** [comment]
SatpalSandhu61 
I run 7nodes example with raft-init.sh and raft-start.sh. I can send the  private  contract.But I use  eth.getTransactionReceipt(txHash) to get address of contract.It returns null.

**Comment by kengan** [comment]
SatpalSandhu61
I want to know how can I post a private contract with   jsonrpc api.
I use the Nethereum Quorum to submit a private contract. I find  Nethereum Quorum will post following json to  Quorum

{"id":1,"jsonrpc":"2.0","method":"eth_sendTransaction","params":[{"privateFor":["ROAZBWtSacxXQrOe3FGAqJDyJjFePR5ce4TSIzmJ0Bc="],"from":"0xed9d02e382b34818e88b88a309c7fe71e65f419d","gas":"0x47b760","gasPrice":"0x0","value":"0x2a","data":"0x6060604052341561000f57600080fd5b604051602080610149833981016040528080519060200190919050505b806000819055505b505b610104806100456000396000f30060606040526000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff1680632a1afcd914605157806360fe47b11460775780636d4ce63c146097575b600080fd5b3415605b57600080fd5b606160bd565b6040518082815260200191505060405180910390f35b3415608157600080fd5b6095600480803590602001909190505060c3565b005b341560a157600080fd5b60a760ce565b6040518082815260200191505060405180910390f35b60005481565b806000819055505b50565b6000805490505b905600a165627a7a72305820d5851baab720bba574474de3d09dbeaabc674a15f4dd93b974908476542c23f00029"}]}

the value of  gas and   data is  equal to the content in private-contract.js
the value of gasPrice=0 and the value of value=42. All of them are be hex by   Nethereum Quorum.


I post above json  with  PostMan and get the error in log, the content as following
TX failed, will be removed               hash=82f97b…ef4617 err="insufficient balance for transfer"
INFO [07-06|06:04:47] Not minting a new block since there are no pending transactions 

Can you tell me how can I post the private contract by api  not by the command? Thank you !

**Comment by kengan** [comment]
I use the Nethereum Quorum to submit a private contract and also get the error 
TX failed, will be removed hash=82f97b…ef4617 err="insufficient balance for transfer"
INFO [07-06|06:04:47] Not minting a new block since there are no pending transactions

the privcate contract can not be mined.

**Comment by fixanoid** [comment]
Hey gents, are you testing on the fork you created for yourselves? If so, please re-test in quorum-examples with master first to confirm that this is not an error in the implementation you've forked.

**Comment by jpmsam** [comment]
@kengan please try the below, no need to pass a value for contract calls:

`./stop.sh`
`./raft-init.sh`
`./raft-start.sh`
`curl -X POST --data '{"id":1,"jsonrpc":"2.0","method":"eth_sendTransaction","params":[{"privateFor":["ROAZBWtSacxXQrOe3FGAqJDyJjFePR5ce4TSIzmJ0Bc="],"from":"0xed9d02e382b34818e88b88a309c7fe71e65f419d","gas":"0x47b760","gasPrice":"0x0","data":"0x6060604052341561000f57600080fd5b604051602080610149833981016040528080519060200190919050505b806000819055505b505b610104806100456000396000f30060606040526000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff1680632a1afcd914605157806360fe47b11460775780636d4ce63c146097575b600080fd5b3415605b57600080fd5b606160bd565b6040518082815260200191505060405180910390f35b3415608157600080fd5b6095600480803590602001909190505060c3565b005b341560a157600080fd5b60a760ce565b6040518082815260200191505060405180910390f35b60005481565b806000819055505b50565b6000805490505b905600a165627a7a72305820d5851baab720bba574474de3d09dbeaabc674a15f4dd93b974908476542c23f00029000000000000000000000000000000000000000000000000000000000000002a"}]}' localhost:22000
`

The above should work and after running `eth.getTransactionReceipt`, you should be able to get the contract address.


There is a different issue with pending transactions not clearing up.
