### ISSUE TITLE
The need for passing privatefor during contract creation and/or function calls

### ISSUE THREAD

**Issue by nathanawmk** [Consensys-Incorporated/quorum#452]
#### System information

Geth version: `geth version`
1.7.2

OS & Version: Windows/Linux/OSX
RHEL 

Branch, Commit Hash or Release: `git status`

#### Expected behaviour
1. Only have privateFor during function calls, instead of right now where privateFor is used during both contract creation and function calls in web3-quorum 
2. Nodes that are not in the privateFor parameter during contract creation should not be allowed to update state variables even having access to the smart contract address.

#### Actual behaviour
1. Why is PrivateFor required during contract creation? Would passing privatefor during function calls suffice?

2. Inconsistent state observed. A contract was created by node 1 intended for node 2 and node 7 (privateFor node 2 and node 7). Node 3 and Node 4 was able to update the state but not retrieve it -- not able to retrieve the variable is understandable but being able to update the state variable cannot be understood as this contract was created intended for node 2 and node 7. After updating the state variable via node 3 & 4, node 2 and node 7 was getting the most updated value i.e., correct. However, node 1 was still getting the old, i.e., stale value. 

Any thoughts and ideas for the above 2 questions? 

#### Backtrace

````
[backtrace]
````

**Comment by fixanoid** [comment]
Hey @nathanawmk 
for 1 -- privateFor is required to create private state contracts that are only shared between participating parties. privateFor is then only going to work on the contracts that were created with privateFor, ie, it only works on the private smart contracts.

**Comment by fixanoid** [comment]
For 2. A private contract is now only shared between the defined nodes: 1, 2, and 7 because of the privateFor during contract creation. The contract only exists on these nodes. On the other nodes, since they were not party to the privateFor during contract creation, contract pay load does not exist so there is no such contract. You may share abi and contract address, and this will execute in solidity, but it will not affect the private contracts on the originally defined nodes.

**Comment by nathanawmk** [comment]
Thanks for the clarifications!
