### ISSUE TITLE
Key Generation for accounts

### ISSUE THREAD

**Issue by AyushKaul** [Consensys-Incorporated/quorum#550]
I'm new to Quorum. Going through the documentation I found that every Node has a transaction manager. My doubt is that each account that is created on the node uses the same transaction manager ? Also does each account have its separate key pair ?

**Comment by preetgsanand** [comment]
I am gonna go and assume you are talking about **accounts hosted in quorum node** here. Just to give a broader context, accounts hosted in quorum node are a combination of key pairs where as constellation also hosts key pairs.

1. Each account hosted in that quorum node uses the same transaction manager since that quorum node is attached to a specific constellation node which in turn is attached to a specific transaction manager.
2. Accounts hosted on quorum node do not have a mapping to constellation key pair. Account in general do not have a mapping to any quorum node. You can use different accounts to perform transaction in same quorum node or same account to perform transactions in different quorum node. However, your quorum node has a mapping to constellation key pair.

**Comment by AyushKaul** [comment]
> Each account hosted in that quorum node uses the same transaction manager since that quorum node is attached to a specific constellation node which in turn is attached to a specific transaction manager.

Correct me if I'm wrong, Every account created on the same node will be able to see the private transactions within the accounts of the same node. For example we create 3 accounts A, B, C on the node. Make a private transaction between A and B, In that case C will be able to see that private transaction as well. I think the reason for this is the local state maintained as per every node.

**Comment by preetgsanand** [comment]
We are fundamentally talking about different accounts here. Ethereum accounts are used for performing transactions (public/private) but the private transactions are actually made using constellation key pair which are node specific. So when you say, "make a private transaction between A and B", those A and B are nodes (hosting the constellation keys between whom the private transaction is being performed) and not accounts.

**Comment by AyushKaul** [comment]
@vince16  agree with what you're saying. But here I'm talking about accounts only.

> Make a private transaction between A and B, In that case C will be able to see that private transaction as well.

This can be an problem if we want to carry out private transactions within an organisation and we don't want everyone to see the transactions. I can think of a number of use cases where this can be a problem.

**Comment by prd-fox** [comment]
As mentioned, there are two types of keys in a Quorum setup:

Quorum/Ethereum wallet addresses - these are the keys/addresses used to make the transactions between the Quorum nodes and on the blockchain.

Constellation/Tessera keys - these are the keys that are used to specify privacy.

A particular transaction manager can host multiple sets of keys (say A, B and C), in which case it can receive private transactions for each of those keys. Logically, a Quorum+TransactionManager pair represents a single entity within the network. If that single entity is hosting the keys A, B and C, then you are correct in that transactions sent to A or B would be visible by C as well. 

This is generally deemed okay since all the transactions, although sent to different keys, are for the same entity - that single entity would want to be able to see all their private transactions. If there is a need for C's transactions to not be visible to A and B, then you are essentially splitting that one entity into two (even though they may both have the same owner behind the scenes). In this case, it is as simple as setting up a second Quorum/PTM pair that only hosts key C, and the original only hosts keys A and B.

**Comment by princesinha19** [comment]
> In this case, it is as simple as setting up a second Quorum/PTM pair that only hosts key C, and the original only hosts keys A and B

@prd-fox By setting up a second Quorum/PTM pair do you mean that we should make a separate node for C ?

**Comment by fixanoid** [comment]
@ayushkaul95 I've explained this in a bit more detail on the other ticket here: https://github.com/jpmorganchase/quorum/issues/551#issuecomment-428647143

Currently a Quorum node contains a single public and a single private state. Any ethereum account privy to accessing the node in question will be able to see the latest state of the blockchain simply because it has access and it could then also transact on the given private state. Our recommendation for this is to ensure that every private contract also checks which account is allowed to change its state (to curtail unauthorized state change), but theres no preventing from seeing the current state for anyone able to access this node. We don't see this changing in the short term as the one of the primary ideas of Quorum is to maintain a single blockchain containing public and private states.

@princesinha19 you are correct that every party that needs private state must run its own node pair.

**Comment by AyushKaul** [comment]
@fixanoid Thanks for clarification.
