### ISSUE TITLE
Bad block issue and quorum restarts

### ISSUE THREAD

**Issue by Himanshu-Pandey** [Consensys-Incorporated/quorum#576]
#### System information

Geth version: `geth version`

OS & Version: OSX

Branch, Commit Hash or Release: `4d015bb4880c564865d676af0c2a22ddd20c0070`

#### Expected behaviour

Quorum should not stop

#### Actual behaviour

Quorum stops and logs says ##### BAD BLOCK #####

#### Steps to reproduce the behaviour

Don't know the exact steps

#### Stack trace
2018-11-22 12:33:24,439 DEBG 'geth' stdout output:
ERROR[11-22|12:33:24] 
########## BAD BLOCK #########
Chain config: {ChainID: 2018 Homestead: 1 DAO: <nil> DAOSupport: false EIP150: 2 EIP155: 3 EIP158: 3 Byzantium: 1 IsQuorum: true Engine: unknown}

Number: 503
Hash: 0x8488a47523070c2b6ace7bec5d5e3843b7c30883064659245e5527b937d07ae1

Error: gas limit reached
##############################

2018-11-22 12:33:24,447 DEBG 'geth' stdout output:
panic: failed to extend chain: gas limit reached

goroutine 172 [running]:
github.com/ethereum/go-ethereum/raft.(*ProtocolManager).applyNewChainHead(0xc420474dc0, 0xc4202e47e0)
/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/raft/handler.go:887 +0x898
github.com/ethereum/go-ethereum/raft.(*ProtocolManager).eventLoop(0xc420474dc0)
/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/raft/handler.go:741 +0x5e5
created by github.com/ethereum/go-ethereum/raft.(*ProtocolManager).startRaft
/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/raft/handler.go:496 +0x789

2018-11-22 12:33:24,463 DEBG fd 10 closed, stopped monitoring <POutputDispatcher at 139802505636104 for <Subprocess at 139802505849312 with name geth in state RUNNING> (stdout)>
2018-11-22 12:33:24,463 INFO exited: geth (exit status 2; expected)
2018-11-22 12:33:24,463 DEBG received SIGCLD indicating a child quit

**Comment by SatpalSandhu61** [comment]
Are you able to give some information to try and reproduce this?
Was it a large number of transactions, or some transactions requiring large gas amounts?

**Comment by Himanshu-Pandey** [comment]
@SatpalSandhu61 this occurred when I am doing few transactions in parallel.

**Comment by Himanshu-Pandey** [comment]
looks like #330

**Comment by SatpalSandhu61** [comment]
If you are able to retrieve the following information for the block that failed (number 503), it would really help:
- gasLimit
- gasUsed
- number of transactions in the block
- the value of gasUsed for each transaction
- whether any of the transactions in the block were private

If my initial understanding of the issue is correct then some the nodes showing the "BAD BLOCK" error will have crashed, but the node that minted the block should still be running and you should be able to attach to that node to get this information.

**Comment by preetgsanand** [comment]
Information for block ( 503 ) : 
gasLimit : 113063635
gasUsed : 0
transactions: ["0x81700c34e5e4a22b1f866b6319bb8606afc71a3f95df6e69ef3c658f262bc260", "0x1010b78cba2313ec2d9eed3fa0772ea672571e2baae6812518a16c91c570df3e"]

Transaction ( 0x81700c34e5e4a22b1f866b6319bb8606afc71a3f95df6e69ef3c658f262bc260 - Private Transaction ) details  : 
gas: 100000000
gasPrice: 0
cumulativeGasUsed: 0

 Transaction ( 0x1010b78cba2313ec2d9eed3fa0772ea672571e2baae6812518a16c91c570df3e - Private Transaction ) details  : 
gas: 100000000
gasPrice: 0
cumulativeGasUsed: 0

**Comment by SatpalSandhu61** [comment]
Just to let you know that I'm still investigating this issue and also attempting to reproduce it.
In the meantime please let me know what Quorum version you are using.

**Comment by pmitra43** [comment]
We are using version 2.1.1 of quorum. If it helps, this is the genesis block:
```
{
  "alloc": {

  },
  "coinbase": "0x0000000000000000000000000000000000000000",
  "config": {
    "chainId": 1912,
    "byzantiumBlock": 1,
    "homesteadBlock": 1,
    "eip150Block": 2,
    "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "eip155Block": 3,
    "eip158Block": 3,
    "isQuorum":true
  },
  "difficulty": "0x0",
  "extraData": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "gasLimit": "0x5F5E100",
  "mixhash": "0x00000000000000000000000000000000000000647572616c65787365646c6578",
  "nonce": "0x0",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "timestamp": "0x00"
}
```

The gasLimit set here is same as the gasLimit being provided for every transaction from the API, with gasPrice set to 0

**Comment by SatpalSandhu61** [comment]
I believe this issue is similar to # 562 and is related to an inconsistency in the gas calculation for private transactions, depending on whether the node is party to the transaction or not.
I’ve managed to reproduce this; note that nodes which are party to the transaction are the only ones to crash, not the non-participant nodes (which is contrary to what you said on Slack).

The scenario under which this occurs is as follows:
- The minting node is not party to these transactions and calculates the gas required based on the public hash of the contract. One important point here is that you have set the Gas Limit to 100,000,000 and the gas on each transaction is also specified as 100,000,000. When calculating the gas used for the block, the node initially needs to use the supplied transaction gas; then after processing the transaction it deducts the actual gas used from the block Gas Limit. Based on this gas calculation, the minting node accepts multiple transactions into the block (I’ve observed 2 to 3 transactions being minted into a block).
- The problem comes when the new block is received and validated by a node that is party to the transaction. In this case, the gas required is based on the actual contract data, not the public hash. This causes it to overflow the block Gas Limit and it throws the BAD BLOCK error.

As a workaround, I would suggest you use a much larger gas limit. Is there any reason you have the Gas Limit set to the same value as the transaction gas? That doesn’t sound like a good idea to me.
In the meantime I’ll work on a fix for this, as I suspect it will need an additional change to that for #562.

**Comment by SatpalSandhu61** [comment]
BTW the following settings cause the error to occur with higher likelyhood, due to them resulting in higher gas usage:
```
    "homesteadBlock": 1,
    "eip150Block": 2,
```

**Comment by Himanshu-Pandey** [comment]
does https://github.com/jpmorganchase/quorum/pull/584 fixes this issue @SatpalSandhu61 ?

**Comment by SatpalSandhu61** [comment]
No, that is a different issue (although it is related).
To avoid the issue you need to ensure you specify a sufficiently large gasLimit in your genesis block.

**Comment by fixanoid** [comment]
@Himanshu-Pandey your genesis looks to be generated from istanbul-tools. This makes me think that Quorum used may be out of date as well, please check your version and ensure its either master or 2.1.1 as this error may be triggered by a great number of things that have been fixed recently.

@pmitra43 and @vince16 please open separate tickets for tracking. Thank you.

**Comment by Himanshu-Pandey** [comment]
@fixanoid  my quorum is latest version i.e 2.1.1 only, and can you please let me know what do I need to change in genesis so that I don't face this issue again.

**Comment by fixanoid** [comment]
@Himanshu-Pandey, @SatpalSandhu61 has identified and is working on a related defect, that said, as mentioned, gas limit has to be set a lot higher, when in doubt, please use quorum-examples genesis values: https://github.com/jpmorganchase/quorum-examples/blob/master/examples/7nodes/genesis.json#L31
