### ISSUE TITLE
How to locally compute a hash of a private transaction?

### ISSUE THREAD

**Issue by mushketyk** [Consensys-Incorporated/quorum#657]
Is it possible to compute a hash of a private transaction of the client side without relying on a transaction hash returned from Quorum?

If a hash of a transaction cannot be computed locally, there is a change that a transaction will be added to a mempool, but a client will get an error (e.g., because of a network partition) or simply fail and won't be able to record that a transaction was submitted. In case of an error, the only recourse for a client would be to re-submit the transaction which can, in adverse circumstances, result in two transactions being executed instead of one.

I was trying to use the `ethereumjs-tx` library to compute a hash of a private transaction locally, but the hash returned by Quorum was always different. Here is the description of the issue: https://github.com/ethereumjs/ethereumjs-tx/issues/141

If I understand this correctly, it is impossible at the moment, because Quorum replaces a body of a private transaction with its hash and then hashes the result transaction.

Is there a way to compute a hash of a private transaction locally?

**Comment by prd-fox** [comment]
As you say, this is because Quorum replaces the data field of a transaction with a hash. This hash is generated by the Private Transaction Manager, and will be different every time, with no way to guess what it might be.

Look into [Quorum.js](https://github.com/jpmorganchase/quorum.js) and Private Raw Transactions, which will allow you have a private transaction that you can calculate the hash of before sending it in. This may require some looking at the source to prevent auto-sending of the signed tx, but the code should be straightforward to follow.
