### ISSUE TITLE
Quorum geth for raspberry pi

### ISSUE THREAD

**Issue by felison692** [Consensys-Incorporated/quorum#661]
Hi, is it possible to compile geth for using in a raspberry pi 3?

**Comment by SatpalSandhu61** [comment]
Yes. Whilst I haven't tried it, I'm aware that folks have done this and you can find articles on the internet describing how to do it for Ethereum (Quorum will be the same). My suggestion would be to install Ubuntu on the Rasberry and follow the normal steps for building Quorum.

**Comment by felison692** [comment]
I havent found any guide to compile quorum client for raspbian, so I have open this thread.
¿Why is it closed?

**Comment by fixanoid** [comment]
@felison692 a guide for Quorum doesnt exist separately at the moment, but since its a geth fork, you can follow the same instructions but with the source code form this repo.

Here are build instructions I found that may be helpful:
- Cross-compilation instructions: https://github.com/ethereum/go-ethereum/wiki/Cross-compiling-Ethereum. You are likely going to need ARM builds
- additional cli instructions that may be useful: https://owocki.com/install-ethereum-geth-raspberry-pi-b/ and https://ethereum.stackexchange.com/questions/31610/how-to-install-geth-on-rpi-3b
