### ISSUE TITLE
Reducing number of nodes and disabling private transactions

### ISSUE THREAD

**Issue by romisalve** [Consensys-Incorporated/quorum#666]
Hello, 

I want to know how can I reduce the number of nodes of the quorum 7 nodes example network if I am running it through docker. 

Also, I need to disable private transactions. I found that I need to set PRIVATE_CONFIG as _ignore_ , where should I do that.

Thank you!

**Comment by SatpalSandhu61** [comment]
To reduce the number of nodes you'll need to modify the following:
- modify the relevant start script to remove the startup for the unwanted nodes (e.g. raft-start.sh)
- modify permissioned-nodes.json to remove the unwanted nodes
- you may also want to remove unwanted nodes from the relevant init script (e.g. raft-init.sh), but that's not strictly necessary.

PRIVATE_CONFIG is an environment variable. It's actually set in the start script to point to the relevant ipc file. You just need to set it to "ignore".

You should find this useful: https://github.com/jpmorganchase/quorum/wiki/From-Scratch

**Comment by romisalve** [comment]
Thank you! But if I am running the example from Docker, should i make those changes on docker-compose.yml or where should I modify something?

THank you!!

**Comment by SatpalSandhu61** [comment]
Ah apologies, I missed that.
In that case, you need to edit the "docker-compose.yml" file. Under "services" you need to remove the entire section for the nodes and txmanagers that you do not want to run (e.g. "node7" and "txmanager7".

**Comment by romisalve** [comment]
Ok! THank you! And another question on that docker-compose.yml, if I want to use the 7nodes example network and deploy a dapp on it, should I change the IP directions or something? 

And also, by using the docker option I am initializing a network of 7 nodes. What should I do if I want to add another node? I would need to run everything from scratch? Can this example be use for production?

Thank you!

**Comment by SatpalSandhu61** [comment]
You should be able to use the 7Nodes example 'out of the box'. No changes would be needed in order to run it or deploy a dapp. It comes with an example of a public contract that you can try: "public-contract.js".

To add another node is similar to my description for removing a node - edit the docker-compose.yml and add the details for the new node(s). You'll need to read the link I pasted earlier to understand what is involved in adding new nodes: https://github.com/jpmorganchase/quorum/wiki/From-Scratch

With regards to production, the examples are really meant to get folks up and running and help them to evaluate and determine the best solution for them. You could certainly run this in production but it really depends on your use case and business area. There are a number of things that you may need to consider, such as resiliency, scaleability, security etc. For these kinds of questions and advice, I suggest you follow our slack channel and post questions there: go-quorum.slack.com
Good luck!
