### ISSUE TITLE
Quorum with Raft consensus

### ISSUE THREAD

**Issue by wenhuancai** [Consensys-Incorporated/quorum#696]
Hi there:
（1）i get the err:
Fatal: Raft-based consensus requires either (1) an initial peers list (in static-nodes.json) including this enode hash (fe613c994b049274d5494f412b225ab42878ab3319215ee93fea712f9a7519ec), or (2) the flag --raftjoinexisting RAFT_ID, where RAFT_ID has been issued by an existing cluster member calling `raft.addPeer(ENODE_ID)` with an enode ID containing this node's enode hash.
（2）and i run the  PRIVATE_CONFIG=tm.ipc nohup geth --datadir new-node-1 --nodiscover --verbosity 5 --networkid 31337 --raft --raftport 50000 --rpc --rpcaddr 0.0.0.0 --rpcport 22000 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,raft --emitcheckpoints --port 21000 2>>node.log &. 
i can't get the tmp.ipc.

**Comment by SatpalSandhu61** [comment]
That error means you haven't specified any peers for the Raft network. As per the error message you need to specify the peers via one of the mechanisms listed.
See the documentation here: [Initial configuration, and enacting membership changes](https://github.com/jpmorganchase/quorum/blob/master/docs/raft.md#initial-configuration-and-enacting-membership-changes)

Because of that error, geth is not starting up; hence there is no tmp.ipc available.
