### ISSUE TITLE
Istanbul Consensus Liveness when roundchange without hashlock

### ISSUE THREAD

**Issue by nambrot** [Consensys-Incorporated/quorum#711]
Howdy,

we are currently evaluating Istanbul consensus as well and during said evaluation we found an issue that we would like to run by the Quorum team. A test case and a tentative fix can be found at 

https://github.com/jpmorganchase/quorum/compare/master...nambrot:no-preprepare-wo-lock

Specifically, it appears to us that Istanbul currently does not send out of `PREPREPARE` upon a successful round change, unless the next proposer has achieved hashlock with quorum `PREPARE`s prior.

**Comment by drequinox** [comment]
Thanks for your contribution. The scenario mentioned in your post cannot occur because If round change is true and I am also the proposer and there's some request already pending then the logic is to check if there's already a locked block present, if yes, then it will propose that again, otherwise it will propose the pending request which in fact is the proposal which the validator has proposed in previous round.
see for reference:
- the logic for checking if something is pending
https://github.com/jpmorganchase/quorum/blob/e80b29695b6adc584290bba06ab8aac7c658a0b7/consensus/istanbul/core/core.go#L252

- this is where it's handled
https://github.com/jpmorganchase/quorum/blob/e80b29695b6adc584290bba06ab8aac7c658a0b7/consensus/istanbul/core/request.go#L35

**Comment by nambrot** [comment]
Thank you for your response and the references. If I may ask one more question in regards to 

> otherwise it will propose the pending request which in fact is the proposal which the validator has proposed in previous round.

In a round-robin policy, the validator who is the current proposer after a round-change has not proposed any blocks prior (or holds onto the proposal of a different validator)? However if I understood you correctly, a pending request is basically stored by all validators from their miner/worker, but only send out as a `PREPREPARE` if one is the proposer for the current round, or if one becomes the proposer after a round change?

**Comment by jbhurat** [comment]
Hi @nambrot, to add on to what @drequinox mentioned above, at the beginning of each new sequence  (block) every validator collects transactions from transaction pool and creates a block out of it and stores it as `pendingRequest`. 

When a new round is started, it checks if the current proposer is locked on a block, in that case it proposes the block which it is currently locked on as shown in https://github.com/jpmorganchase/quorum/blob/e80b29695b6adc584290bba06ab8aac7c658a0b7/consensus/istanbul/core/core.go#L255-L259

If that proposer is not locked on any block, it will propose the block which it had previously stored in its `pendingRequest` as shown in https://github.com/jpmorganchase/quorum/blob/e80b29695b6adc584290bba06ab8aac7c658a0b7/consensus/istanbul/core/core.go#L260-L262

The above 2 cases handle the scenarios where a validator is locked on a block or it is not locked on a block and as such I don't believe there is a liveness issue here.

**Comment by jbhurat** [comment]
Closing the ticket. Please reopen if you have any additional questions

**Comment by nambrot** [comment]
Thank you for the explanation!
