### ISSUE TITLE
Use of MD5, which is a weak cryptographic primitive

### ISSUE THREAD

**Issue by 0xmountaintop** [Consensys-Incorporated/quorum#757]
Currently in `cmd/swarm/export_test.go`, `cmd/swarm/swarm-smoke/feed_upload_and_sync.go` and `cmd/swarm/swarm-smoke/upload_and_sync.go` ,  md5 is used for digest.   This should be avoid as it's a weak cryptographic primitive, and it's easy to be collided.

**Comment by prd-fox** [comment]
Swarm was inherited as part of the the upstream Geth repo, and isn't used in Quorum. Swarm has been removed upstream now, so when we upgrade we will have these removed too.
If you want to check if the issue is still present within Swarm, the repo is now located at https://github.com/ethersphere/swarm
