### ISSUE TITLE
Will there be compatibility issues with Quorum and Ethereum 2.0 ?

### ISSUE THREAD

**Issue by freedomtrain** [Consensys-Incorporated/quorum#820]
Will there be compatibility issues with Quorum and Ethereum 2.0 ?

**Comment by fixanoid** [comment]
Hi. Ethereum 2.0 is largely an upgrade to the consensus mechanism. Since
Quorum uses completely separate implementation of consensus algorithms,
this upgrade is by an large will unaffect Quorum. That said, we are keeping
track and integrating evm and other changes as the protocol moves forward.
Quorum will remain compatible with Ethereum in terms of development
languages, tooling, and evm.

**Comment by freedomtrain** [comment]
Thanks so much for your help !
