### ISSUE TITLE
miner always "0x0000000000000000000000000000000000000000"

### ISSUE THREAD

**Issue by dvgoyeneche** [Consensys-Incorporated/quorum#824]
I have miner="0x0000000000000000000000000000000000000000" in all my blocks in quorum.
¿Is this normal?

**Comment by zzy96** [comment]
For Raft, `miner` is always "0x0000000000000000000000000000000000000000". For IBFT and Clique, `miner` is used to store the candidate address of vote.

**Comment by dvgoyeneche** [comment]
Thanks! How can we know who has mined the block?

**Comment by zzy96** [comment]
In Ethereum, we need to know who is the miner which is an Ethereum account for block reward (That's why we have this miner field). However, the new block is actually propagated by node. So your question should become "which node has mined the block". Then the answer is: For Raft, it is always the leader node. You can check node role with `raft.role`. For IBFT, every round one of the validator nodes will propose block. For Clique, miner nodes will try to seal the block with its coinbase account if it is in the signer list. You may also trace the log to get which node actually mined the block.

**Comment by fixanoid** [comment]
To add to @zzy96 answer. Raft block header contains sealer information that could be used to recover raft id of the minter. See: https://github.com/jpmorganchase/quorum/blob/master/raft/minter.go#L428
