### ISSUE TITLE
how geth and constellation communicate

### ISSUE THREAD

**Issue by dvgoyeneche** [Consensys-Incorporated/quorum#839]
Hi there,

In our nodes we start geth and constellation processes.
¿How do geth know the port used by constellation in the node?

Thanks in advance

**Comment by prd-fox** [comment]
Quorum talks to Constellation via a unix socket file only.
The location of this file is provided to Quorum via the environment variable `PRIVATE_CONFIG`.

For reference, the [7nodes start script](https://github.com/jpmorganchase/quorum-examples/blob/59643208d042d4e6ada00d9b0eb1ba8c3ac198f9/examples/7nodes/istanbul-start.sh#L94) provides this environment variable.

You tell Constellation where to create this file by supplying the `--socket=...` CLI option, or in the Constellation configuration file.

**Comment by dvgoyeneche** [comment]
In a console, echo $PRIVATE_CONFIG returns no data

**Comment by prd-fox** [comment]
In the case of the example scripts linked above, the environment variable is set on the same line as invoking the `geth` application, which means the envvar is only set for the scope of that one command, and isn't visible outside that.

Otherwise, it is expected that you set the variable yourself, depending on how you have set up your local node.

**Comment by dvgoyeneche** [comment]
Thanks Peter, its is working correctly. You can close the issue
