### ISSUE TITLE
async contract deployment does not invoke callback function when using --raft

### ISSUE THREAD

**Issue by younanjo** [Consensys-Incorporated/quorum#86]
I'm trying to deploy a simple smart contract while running qurom in raft mode. 

If my code looks like so:

`

      var contract = web3.eth.contract(source.info.abiDefinition);
      const options = {
        from: config.gethAccount,
        data: compiled.code,
        gas: 4000001,
      };

      var myContractReturned = contract.new(options, function(err, myContract){
        if(!err) {
          if(!myContract.address) {
            console.log(myContract.transactionHash) // The hash of the transaction, which deploys the contract
            
          } else {
            console.log(myContract.address) // the contract address
          }
        }
        else {
          throw new Error(err)
        }
      });
`

I get a transaction hash, and i can see that the transaction hash has a receipt (eth.getTransactionReceipt()), however the callback function isn't called the second time to get the actual contract address. Is this because raft is quicker than web3 polling interval/sleep? 

Above code works fine in normal (non-raft) mode.

**Comment by patrickmn** [comment]
PR: https://github.com/jpmorganchase/quorum/pull/85

**Comment by patrickmn** [comment]
The PR 85 fix has been merged to master.

**Comment by younanjo** [comment]
I just rebuilt from latest master. Still same issue. The callback isn't called in `--raft`.

**Comment by tylobban** [comment]
hi @younanjo, please let us know the geth version? run `geth version` from terminal. Thanks.

**Comment by younanjo** [comment]
```
VERSION:
   1.5.0-unstable-e3a0ae27
```

**Comment by tylobban** [comment]
@younanjo can you please log into the js console and try loadScript("script1.js")?  That script also has the callbacks and we can see that both are fired so would like you to confirm the same.

**Comment by tylobban** [comment]
@younanjo please confirm this can be closed?

**Comment by tylobban** [comment]
@younanjo closing this issue as we have not heard from you. Please re-open if the suggested action above does not work.

**Comment by dan-turner** [comment]
Hey guys, might need to re-open this one.  The fix is intermittent.  As part of doing some robustness tests on Quroum we're deploying the same contract over and over again in a loop:

https://github.com/CBAInnovationLab/web3-sandbox

The first time I ran it, it failed on the 5th iteration, the next time I ran it, it failed on the 167th iteration.

```
<snipped>

Deploying: SimpleStorage [165]
{ jsonrpc: '2.0', id: 1500271908998, result: '0xce8' }
- Waiting to be mined... Tx Hash: 0x14f41038ca508c4aff0e0eb17696dfe892aeda5b34d53493ae89e366acbda17d
- Mined! Address: 0x404aee1f1f965ee56c8f9dacc14c97dcc0d10604
- Stored Data: 165
Deploying: SimpleStorage [166]
{ jsonrpc: '2.0', id: 1500271909620, result: '0xce9' }
- Waiting to be mined... Tx Hash: 0x941c56283c7ad5e7888b7924e796cbb16d78a1be1ff5d128c35643f6c707e9c4
- Mined! Address: 0x233f1b5525e597696eafedabbde460ac9c658f4a
- Stored Data: 166
Deploying: SimpleStorage [167]
{ jsonrpc: '2.0', id: 1500271910238, result: '0xcea' }
- Waiting to be mined... Tx Hash: 0xd69a6f9fa993478de9d706366263d38f82bab227e06977e87eafaa3c8ad6c305

<froze here>
```

Results:
```
geth attach http://localhost:8545
Welcome to the Geth JavaScript console!

instance: Geth/v1.5.0-unstable-ddb011f3/linux/go1.7.3
 modules: admin:1.0 debug:1.0 eth:1.0 net:1.0 personal:1.0 quorum:1.0 rpc:1.0 txpool:1.0 web3:1.0

> eth.getTransactionReceipt('0xd69a6f9fa993478de9d706366263d38f82bab227e06977e87eafaa3c8ad6c305')
{
  blockHash: "0xea496ac9faed12a16f788ffb8ad208f8ca4c956634d0186eeefab95500188bf7",
  blockNumber: 1536,
  contractAddress: "0x21c4361894d9378ebec3b52514a23a65b21b4904",
  cumulativeGasUsed: 128226,
  from: "0xbfdacdfe79ccf1e61649220df47701df16606405",
  gasUsed: 128226,
  logs: [],
  logsBloom: "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  root: "0x6cddb1b09c30c2f1803bc2cc6864b69454ce7f9f22cf141bea47050858002670",
  to: null,
  transactionHash: "0xd69a6f9fa993478de9d706366263d38f82bab227e06977e87eafaa3c8ad6c305",
  transactionIndex: 0
}
```

**Comment by dan-turner** [comment]
Ok, I've tracked down the problem. The problem is not with Quorum, the problem is with web3.js. Quorum is too fast for it :).

### The Problem
1. The tx is sent here: https://github.com/ethereum/web3.js/blob/develop/lib/web3/contract.js#L214
1. Web3 then calls `checkForContractAddress`: https://github.com/ethereum/web3.js/blob/develop/lib/web3/contract.js#L224
1. Which only **then** starts a 'new block' watch: https://github.com/ethereum/web3.js/blob/develop/lib/web3/contract.js#L101

The problem is that the tx has already been finalised, and with quorum only producing blocks as it receives txs, the watch is not triggered again.

### The Fix
https://github.com/CBAInnovationLab/web3.js/commit/6307b63b0808be0634930e4b7a3cf983cbfa0d53

We refactored `web3.js` to **not** use a `filter` (they are evil anyway - a potential memory leak and not possible to load balance) and instead implemented our own polling approach.  Also, rather than timing out after 50 blocks, we chose to timeout after 30 seconds.

**PLEASE NOTE:** This approach works well for Quorum/Ethermint where we have fast, deterministic block times. This refactor would not work well with the public Ethereum chain as there will be many valid cases where a contract has not been mined within 30 seconds.  I'm considering submitting a similar patch to the `web3.js` upstream, that ditches filters, but still uses 50 blocks as the timeout.

### See For Yourself
1. Clone https://github.com/CBAInnovationLab/quorum-examples
1. `cd quorum-examples/examples/7nodes`
1. `docker-compose up`
1. Clone https://github.com/CBAInnovationLab/web3-sandbox
1. `cd web3-sandbox`
1. `yarn`
1. `yarn contracts:deploy`

**Comment by ShaleenThapa** [comment]
I'm also falling into the same issue. For my project, I create the contract and then needed to have the contract's address, then some other processing.. however the whole logic fails as the callback function does not get the address back properly.

Any clues???

**Comment by moda20** [comment]
Does this issue still exits in web3.js 1.0  version ?

**Comment by jpmsam** [comment]
@ShaleenThapa It seems that you had a different issue where receipts weren't being populated properly.
