### ISSUE TITLE
 goroutine 1 [running]: github.com/arduino/arduino-cli/legacy/builder.ResolveLibrary(0x134c85a0, 0x137f693c, 0xf, 0x137f693c) 	/home/jenkins/workspace/arduino-builder-all-cross-cli-inception/src/github.com/arduino/arduino-cli/legacy/builder/resolve_library.go:64 +0x14b

### ISSUE THREAD

**Issue by kumarsatish2012** [Consensys-Incorporated/quorum#871]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth version`

OS & Version: Windows/Linux/OSX

Branch, Commit Hash or Release: `git status`

#### Backtrace

````
[backtrace]
````

**Comment by SatpalSandhu61** [comment]
I'm assuming the title of this ticket is the error message for the other ticket you raised (number 870).
Please add that information into ticket 870 rather than raise a separate ticket.
If this is a different issue then please can you create a ticket with a descriptive title and place the error message, along with full details of the issue into the body of the ticket.
Thanks.
(I'm closing this ticket).
