### ISSUE TITLE
Latest version breaks DNS name support in static-nodes.json and likely RPC

### ISSUE THREAD

**Issue by fmhall** [Consensys-Incorporated/quorum#921]
#### System information

OS & Version: Linux

Branch, Commit Hash or Release: `docker quorumengineering/quorum:latest`

#### Expected behaviour
Nodes specified using DNS names in `static-nodes.json` to peer with each other, as they had in `docker quorumengineering/quorum:2.4.0`

#### Actual behaviour
Nodes do not peer with each other due to invalid IP addresses. There also seems to be some issues with RPC and DNS but I cannot confirm this.

#### Steps to reproduce the behaviour
Use DNS names in `static-nodes.json` with the latest version and they will not peer with each other. 

#### Backtrace

````
ERROR[12-30|17:06:27.677] Node URL enode://<pub key>@<dns name>:30303?discport=0: invalid IP address
````

**Comment by zzy96** [comment]
Hi @fmhall 

From the ERROR message you provide, this should only come from `ParseV4` in `parsePersistentNodes`. The "invalid IP address" error has been removed from `ParseV4` since DNS hostname is supported in 2.4.0. There is no reason the current master will fail with this error in an upgrade scenario (since the error message is completely gone...). Can you check if your docker image `quorumengineering/quorum:latest` is up-to-date on your local machine?

**Comment by vsmk98** [comment]
Hi @fmhall , can you please share the output of the following command `docker image inspect quorumengineering/quorum:latest`? thanks

**Comment by fmhall** [comment]
The container I was using was not updated to latest
